#810: added warning message to setup explaining that a new shell needs to be started to use IDEasy (#819)

diff --git a/cli/src/main/package/functions b/cli/src/main/package/functions
--- a/cli/src/main/package/functions
+++ b/cli/src/main/package/functions
@@ -30,7 +30,7 @@ function icd() {
     ide init
     return
   elif [ $# -gt 2 ]; then
-    echo -e "\033[93mInvalid usage icd $*\033[39m" >&2
+    echo -e "\033[91mInvalid usage icd $*\033[39m" >&2
     return 1  
   fi
   if [ "$1" = "-p" ]; then
