improved/aligned error messages

diff --git a/cli/src/main/package/setup b/cli/src/main/package/setup
--- a/cli/src/main/package/setup
+++ b/cli/src/main/package/setup
@@ -25,13 +25,13 @@ function doSetupInConfigFile() {
 
 cd "$(dirname "${BASH_SOURCE:-$0}")" || exit 255
 if [ "${PWD/*\//}" != "_ide" ]; then
-  echo -e "\033[93mInvalid installation path $PWD - you need to install IDEasy to a folder named '_ide'.\033[39m" >&2
+  echo -e "\033[93mInvalid installation path $PWD - you need to rename '${PWD/*\//}' to '_ide'.\033[39m" >&2
   exit 1
 fi
 echo "Setting up IDEasy in ${PWD}"
 cd ..
 if [ "${PWD/*\//}" != "projects" ]; then
-  echo -e "\033[93mYour IDE_ROOT folder is $PWD - you need to rename ${PWD/*\//} to 'projects'.\033[39m" >&2
+  echo -e "\033[93mInvalid IDE_ROOT path $PWD - you need to rename '${PWD/*\//}' to 'projects'.\033[39m" >&2
   exit 1
 fi
 export IDE_ROOT=${PWD}
