#512: moved check_status moved check_status step to check for updates workflow file

diff --git a/.github/workflows/check-for-updates.yml b/.github/workflows/check-for-updates.yml
--- a/.github/workflows/check-for-updates.yml
+++ b/.github/workflows/check-for-updates.yml
@@ -32,3 +32,29 @@ jobs:
             -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             https://api.github.com/repos/${{ github.repository }}/actions/workflows/nightly-build.yml/dispatches \
             -d '{"ref":"main"}'
+
+  check_status:
+    runs-on: ubuntu-latest
+    needs: verify_commit
+    if: ${{ needs.verify_commit.outputs.RUN_BUILD == 'false' }}
+    steps:
+      - name: Check last workflow status
+        id: check_status
+        run: |
+          workflow_filename="nightly-build.yml"
+          last_workflow=$(curl -L -H "Accept: application/vnd.github+json" \    
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            "https://api.github.com/repos/devonfw/IDEasy/actions/workflows/$workflow_filename/runs?per_page=1" | jq -r '.workflow_runs[0]')
+          conclusion=$(echo $last_workflow | jq -r '.conclusion')
+          echo "conclusion=$conclusion" >> $GITHUB_ENV
+
+      - name: Print and handle the status
+        run: |
+          echo "The status of the last workflow run is: ${{ env.conclusion }}"
+          if [ "${{ env.conclusion }}" != "success" ]; then
+            echo "The last workflow did not succeed. Failing this workflow."
+            exit 1
+          else
+            echo "The last workflow succeeded. This workflow will succeed."
+          fi
