#427: re-enabled all jobs

diff --git a/.github/workflows/nightly-build.yml b/.github/workflows/nightly-build.yml
--- a/.github/workflows/nightly-build.yml
+++ b/.github/workflows/nightly-build.yml
@@ -1,26 +1,26 @@
 name: Nightly Build
 on:
-  workflow_dispatch
-#  schedule:
-#    - cron: '0 2 * * *'
+  workflow_dispatch:
+  schedule:
+    - cron: '0 2 * * *'
 
 jobs:
-  #  verify_commit:
-  #    runs-on: ubuntu-latest
-  #    name: Verify latest commit
-  #    outputs:
-  #      RUN_BUILD: ${{ steps.verify_commit.outputs.RUN_BUILD }}
-  #    steps:
-  #      - uses: actions/checkout@v3
-  #      - id: verify_commit
-  #        name: Verify latest commit is less than 24 hours
-  #        if: ${{ (github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch') }}
-  #        run: echo '::set-output name=RUN_BUILD::'$(test -n "$(git log --format=%H --since='24 hours ago')" && echo 'true' || echo 'false')
+  verify_commit:
+    runs-on: ubuntu-latest
+    name: Verify latest commit
+    outputs:
+      RUN_BUILD: ${{ steps.verify_commit.outputs.RUN_BUILD }}
+    steps:
+      - uses: actions/checkout@v3
+      - id: verify_commit
+        name: Verify latest commit is less than 24 hours
+        if: ${{ (github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch') }}
+        run: echo '::set-output name=RUN_BUILD::'$(test -n "$(git log --format=%H --since='24 hours ago')" && echo 'true' || echo 'false')
 
   build-documentation:
     name: Build documentation and upload to natives
-    #    needs: [ verify_commit ]
-    #        if: ${{ needs.verify_commit.outputs.RUN_BUILD == 'true' }}
+    needs: [ verify_commit ]
+    if: ${{ needs.verify_commit.outputs.RUN_BUILD == 'true' }}
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -42,13 +42,11 @@ jobs:
 
   build-natives:
     name: Build native images with downloaded documentation
-    needs: [ build-documentation ]
+    needs: [ verify_commit, build-documentation ]
+    if: ${{ needs.verify_commit.outputs.RUN_BUILD == 'true' }}
     runs-on: ${{ matrix.os }}
-    #    needs: verify_commit
-    #    if: ${{ needs.verify_commit.outputs.RUN_BUILD == 'true' }}
     strategy:
       matrix:
-        #        os: [ windows-latest, ubuntu-latest ]
         os: [ windows-latest, ubuntu-latest, macos-latest, macos-13 ]
 
     steps:
@@ -70,7 +68,7 @@ jobs:
         shell: bash
         run: |
           cd cli
-          mvn -B -ntp -P${{ matrix.os }} -DskipTests=true package
+          mvn -B -ntp -P${{ matrix.os }} '-P!build-documentation' -DskipTests=true package
       - uses: actions/upload-artifact@v4
         with:
           name: natives-${{ matrix.os }}
@@ -78,8 +76,8 @@ jobs:
 
   deploy:
     name: Build Project and Deploy
-    needs: [ build-natives ]
-    #    if: ${{ needs.verify_commit.outputs.RUN_BUILD == 'true' }}
+    needs: [ verify_commit, build-documentation, build-natives ]
+    if: ${{ needs.verify_commit.outputs.RUN_BUILD == 'true' }}
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
@@ -95,37 +93,37 @@ jobs:
           pattern: natives-*
       - name: Download natives and build project
         run: |
-          mvn -B -ntp -Dstyle.color=always -P!build-documentation install
+          mvn -B -ntp -Dstyle.color=always install
           mv ./natives-windows-latest/* ./cli/target/
           mv ./natives-ubuntu-latest/* ./cli/target/
           mv ./natives-macos-13/* ./cli/target/
           mv ./natives-macos-latest/* ./cli/target/
-#      - name: Deploy to OSSRH nexus
-#        env:
-#          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
-#          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
-#        run: mvn --settings .mvn/settings.xml -DskipTests=true -Darchetype.test.skip=true -Dmaven.install.skip=true -Dgpg.skip=true -Dstyle.color=always -B -ntp -Pdeploy deploy
+      - name: Deploy to OSSRH nexus
+        env:
+          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
+          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
+        run: mvn --settings .mvn/settings.xml -DskipTests=true -Darchetype.test.skip=true -Dmaven.install.skip=true -Dgpg.skip=true -Dstyle.color=always -B -ntp -Pdeploy deploy
 
-#  check_status:
-#    runs-on: ubuntu-latest
-#    needs: verify_commit
-#    if: ${{ needs.verify_commit.outputs.RUN_BUILD == 'false' }}
-#    steps:
-#      - name: Check last workflow status
-#        id: check_status
-#        run: |
-#          workflow_filename="nightly-build.yml"
-#          last_workflow=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-#            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$workflow_filename/runs?per_page=1" | jq -r '.workflow_runs[0]')
-#          conclusion=$(echo $last_workflow | jq -r '.conclusion')
-#          echo "conclusion=$conclusion" >> $GITHUB_ENV
-#
-#      - name: Print and handle the status
-#        run: |
-#          echo "The status of the last workflow run is: ${{ env.conclusion }}"
-#          if [ "${{ env.conclusion }}" != "success" ]; then
-#            echo "The last workflow did not succeed. Failing this workflow."
-#            exit 1
-#          else
-#            echo "The last workflow succeeded. This workflow will succeed."
-#          fi
+  check_status:
+    runs-on: ubuntu-latest
+    needs: verify_commit
+    if: ${{ needs.verify_commit.outputs.RUN_BUILD == 'false' }}
+    steps:
+      - name: Check last workflow status
+        id: check_status
+        run: |
+          workflow_filename="nightly-build.yml"
+          last_workflow=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/$workflow_filename/runs?per_page=1" | jq -r '.workflow_runs[0]')
+          conclusion=$(echo $last_workflow | jq -r '.conclusion')
+          echo "conclusion=$conclusion" >> $GITHUB_ENV
+
+      - name: Print and handle the status
+        run: |
+          echo "The status of the last workflow run is: ${{ env.conclusion }}"
+          if [ "${{ env.conclusion }}" != "success" ]; then
+            echo "The last workflow did not succeed. Failing this workflow."
+            exit 1
+          else
+            echo "The last workflow succeeded. This workflow will succeed."
+          fi
